/* Simulation code for SimpleDistricHeating.Examples.MultiLoad.Aroma_sim generated by the OpenModelica Compiler OpenModelica v1.19.2 (64-bit). */
#if !defined(SimpleDistricHeating_Examples_MultiLoad_Aroma_sim__MODEL_H)
#define SimpleDistricHeating_Examples_MultiLoad_Aroma_sim__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_functions.h"

#define Modelica_Fluid_Utilities_regRoot_index 0
#define Modelica_Fluid_Utilities_regSquare_index 1

extern void SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
extern void SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_initialNonLinearSystem(int nNonLinearSystems, NONLINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
extern void SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_initialLinearSystem(int nLinearSystems, LINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_checkForAsserts(DATA *data, threadData_t *threadData);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_relationDescription(int i);
extern void SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_function_initSample(DATA *data, threadData_t *threadData);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_initialAnalyticJacobianG(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_initialAnalyticJacobianA(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_initialAnalyticJacobianB(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_initialAnalyticJacobianC(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_initialAnalyticJacobianD(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_initialAnalyticJacobianF(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_functionJacG_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_functionJacA_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_functionJacB_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_functionJacC_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_functionJacD_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_functionJacF_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_linear_model_frame(void);
extern const char* SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_linear_model_datarecovery_frame(void);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_mayer(DATA* data, modelica_real** res, short *);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_setInputData(DATA *data, const modelica_boolean file);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_inputNames(DATA* data, char ** names);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_dataReconciliationInputNames(DATA* data, char ** names);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_functionLocalKnownVars(DATA*, threadData_t*);
extern int SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_symbolicInlineSystem(DATA*, threadData_t*);

#include "SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(SimpleDistricHeating_Examples_MultiLoad_Aroma_sim__MODEL_H) */


