/* Additional record code for SimpleDistricHeating_Examples_MultiLoad_Aroma_sim generated by the OpenModelica Compiler OpenModelica v1.19.2 (64-bit). */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "SimpleDistricHeating_Examples_MultiLoad_Aroma_sim_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

